const NPC_FLAGS: Record<string, string> = {
  Afghanistan: "🇦🇫",
  Bahrain: "🇧🇭",
  Bangladesh: "🇧🇩",
  Bhutan: "🇧🇹",
  Brunei: "🇧🇳",
  Cambodia: "🇰🇭",
  China: "🇨🇳",
  "Chinese Taipei": "🇹🇼",
  "Hong Kong China": "🇭🇰",
  India: "🇮🇳",
  Indonesia: "🇮🇩",
  Iran: "🇮🇷",
  Iraq: "🇮🇶",
  Japan: "🇯🇵",
  Jordan: "🇯🇴",
  Kazakhstan: "🇰🇿",
  "South Korea": "🇰🇷",
  Kuwait: "🇰🇼",
  Kyrgyzstan: "🇰🇬",
  Laos: "🇱🇦",
  Lebanon: "🇱🇧",
  "Macau China": "🇲🇴",
  Malaysia: "🇲🇾",
  Maldives: "🇲🇻",
  Mongolia: "🇲🇳",
  Myanmar: "🇲🇲",
  Nepal: "🇳🇵",
  Pakistan: "🇵🇰",
  Palestine: "🇵🇸",
  Philippines: "🇵🇭",
  Qatar: "🇶🇦",
  "Saudi Arabia": "🇸🇦",
  Singapore: "🇸🇬",
  "Sri Lanka": "🇱🇰",
  Syria: "🇸🇾",
  Tajikistan: "🇹🇯",
  Thailand: "🇹🇭",
  "Timor-Leste": "🇹🇱",
  Turkmenistan: "🇹🇲",
  UAE: "🇦🇪",
  Uzbekistan: "🇺🇿",
  Vietnam: "🇻🇳",
  Yemen: "🇾🇪",
};

export function getNpcFlag(npc: string): string {
  return NPC_FLAGS[npc] ?? "🏳️";
}
